import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio: Sahil Ahmed',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full bg-dark min-h-screen`}>
        <Navbar />
        <div className='mb-14'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
